version: '2'
services:
  mysql:
    build: ./mysql
    restart: unless-stopped
    ports:
      - '33066:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./db:/var/lib/mysql
  php:
    build: ./php
    restart: unless-stopped
    ports:
      - '8099:80'
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
volumes:
  mysql:
