<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/11/21 17:33:25

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=web_db;host=mysql',
  'profiler' => false,
  'username' => 'root',
  'password' => 'pass',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
